import Link from "next/link";
import { Metadata } from "next";
import { getSortedPostsData } from "../lib/posts";

export const metadata: Metadata = {
  title: "AI & Tech Reviews | The Future is Now",
  description: "Discover the best curated tech products, AI tools, and gaming hardware. High-quality reviews to help you make informed decisions.",
};

export default function Home() {
  const allPostsData = getSortedPostsData();

  return (
    <div className="min-h-screen pt-20 pb-12 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto flex flex-col items-center">

      {/* Hero Section */}
      <div className="text-center w-full max-w-4xl pt-16 pb-20 animate-fade-in-up">
        <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight mb-8">
          The Edge of <span className="gradient-text">Modern Tech</span>
        </h1>
        <p className="text-xl md:text-2xl text-gray-400 font-light mb-12 max-w-2xl mx-auto">
          Automated curation, reviews, and analysis of AI, Hardware, and Smart Homes. Wait, actually, let me tell you a secret: entirely generated by AI.
        </p>
        <button className="px-8 py-4 bg-gradient-to-r from-purple-600 to-rose-500 rounded-full text-white font-bold text-lg hover:scale-105 transition-transform duration-300 shadow-[0_0_30px_rgba(244,63,94,0.3)]">
          Explore Latest Reviews
        </button>
      </div>

      {/* Articles Grid */}
      <div className="w-full mt-12 mb-24">
        <div className="flex justify-between items-center mb-10">
          <h2 className="text-3xl font-bold">Trending Articles</h2>
          <span className="text-purple-400 hover:text-purple-300 cursor-pointer transition-colors font-medium">View all &rarr;</span>
        </div>

        {allPostsData.length === 0 ? (
          <div className="w-full text-center p-12 glass-panel">
            <h3 className="text-2xl font-bold text-gray-400">No Articles Yet!</h3>
            <p className="text-gray-500 mt-2">Run the Python BotBlogger to generate your first SEO article.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 w-full">
            {allPostsData.map((article: { slug: string; title: string; category: string; date: string; excerpt: string; image: string }) => (
              <Link href={`/posts/${article.slug}`} key={article.slug} className="block group">
                <div className="glass-panel h-full overflow-hidden transition-all duration-300 border hover:border-purple-500/50 hover:shadow-[0_0_40px_rgba(139,92,246,0.15)] hover:-translate-y-2">
                  <div className="h-48 w-full overflow-hidden relative">
                    <div className="absolute inset-0 bg-gradient-to-t from-[#0f111a] to-transparent z-10 opacity-60"></div>
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={article.image || "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&q=80&w=800"}
                      alt={article.title}
                      className="object-cover w-full h-full group-hover:scale-110 transition-transform duration-700"
                    />
                    <div className="absolute top-4 left-4 z-20 bg-black/60 backdrop-blur-md px-3 py-1 rounded-full text-xs font-semibold uppercase tracking-wider text-purple-300 border border-purple-500/30">
                      {article.category}
                    </div>
                  </div>
                  <div className="p-6">
                    <h3 className="text-2xl font-bold mb-3 group-hover:text-purple-400 transition-colors line-clamp-2">
                      {article.title}
                    </h3>
                    <p className="text-gray-400 line-clamp-3 leading-relaxed">
                      {article.excerpt}
                    </p>
                    <div className="mt-6 flex items-center text-sm font-medium text-rose-400 group-hover:text-rose-300">
                      Read Full Review <span className="ml-2 group-hover:translate-x-1 transition-transform">&rarr;</span>
                    </div>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        )}
      </div>

    </div>
  );
}
